#!/bin/sh
set -e

unset XDG_CONFIG_HOME
unset HOME
export GIT_CONFIG_NOSYSTEM=1

(cd "${1:-.}"

export GIT_WORK_TREE="$PWD"
export GIT_DIR="$GIT_WORK_TREE/.pairon"

while IFS= read -r line; do
  if test "$line" = "___END_OF_MESSAGE___"; then
    echo "=== START PUSHED PATCH ===" >&2
    echo "$patch" >&2
    echo "=== END PUSHED PATCH ===" >&2

    if { echo "$patch" | git am; }; then
      { echo "$patch";echo ___END_OF_MESSAGE___; } >> "$GIT_DIR/produce"
      echo "INFO: Applied patch successfully" >&2
    else
      git am --abort || true
      echo "INFO: Apply patch failed" >&2
      exit 1
    fi
    patch=
  else
    patch="$patch$line
"
  fi
done
)
