#!/bin/sh
set -e

. "$(dirname $(realpath $0))/common.sh"

usage() {
  test -n "$1" && echo >&2 "Error: $1"
  echo >&2 "
USAGE: $SCRIPT_NAME COMMAND OPTIONS

-- COMMANDS  --
$PLUGINS
"
  exit 1
}

PLUGINS="$(cd "$SCRIPT_DIR"; find . -executable -path "./pairon-*" | sed 's/.*pairon-//' | sort | uniq)"
CMD="$1"

if { test -n "$CMD" && echo "$PLUGINS" | grep -Eq "^$CMD$"; }; then
  shift
  exec "$SCRIPT_DIR/pairon-$CMD" $@
else
  usage "No command: '$CMD'"
fi
