#!/bin/sh
set -e

# shellcheck source=common.sh
. "$(dirname "$(realpath "$0")")/common.sh"

usage() {
  test -n "$1" && echo "Error: $1" >&2
  echo "
USAGE: $SCRIPT_NAME COMMAND OPTIONS

-- COMMANDS --
$PLUGINS
" >&2
  exit 1
}

PLUGINS="$(cd "$SCRIPT_DIR" || exit 1; find . -type f -executable -path "./pairon-*" | sed 's/.*pairon-//' | sort | uniq)"
CMD="$1"

if { test -n "$CMD" && echo "$PLUGINS" | grep -Eq "^$CMD$"; }; then
  shift
  exec "$SCRIPT_DIR/pairon-$CMD" "$@"
else
  usage "No command: '$CMD'"
fi
