#!/bin/sh
set -e

# shellcheck source=common.sh
. "$(dirname "$(realpath "$0")")/common.sh"

while test "$1"; do
  case "$1" in
    -n|--no-autosync) no_autosync=1;shift;;
    -*) die "$1 is not an option";;
    *) arg="$1";shift;;
  esac
done
LOCAL="${arg:-.}"

setrepo "$LOCAL"

lock_file="$GIT_DIR/.listen"
if test -f "$lock_file"; then
  die "Already listening on this repo ($lock_file)"
fi
echo $$ > "$lock_file"
touch "$CONSUME_FILE"
trap 'trap - TERM && rm -f "$lock_file" "$CONSUME_FILE"; kill -TERM 0' INT TERM EXIT

REMOTE="$(git remote get-url origin)"
SSH_HOST="${REMOTE%%:*}"
REMOTE_FILE="${REMOTE#*:}"

echo "$REMOTE" | grep -q : && ssh_mode="ssh $SSH_HOST -- "

autosync() {
  (cd "$GIT_WORK_TREE" || exit 1
    fsw . '.pairon|.git' \
      | xargs -L1 -I% sh -c '. "'"$SCRIPT_DIR/sync_patch.sh"'";sync_patch "%"'
  )
}

start_push() {
  info "Pushing"
  while true; do
    tail -f -n0 "$CONSUME_FILE" | $ssh_mode "$REMOTE_FILE/bare-listen" "$REMOTE_FILE/.." || {
      warn "Push failed, rebasing"
      sync_force "$LOCAL"
    }
  done
}

start_pull() {
  info "Listening"
  $ssh_mode tail -f -n0 "$REMOTE_FILE/produce" | while IFS= read -r line; do
    if test "$line" = "___END_OF_MESSAGE___"; then
      hash="$(echo "$patch" | head -n1 | grep -oE "\<[a-f0-9]{40}\>")"
      echo "=== START PULLING PATCH $hash ===" >&2
      echo "$patch" >&2
      echo "=== END PULLING PATCH $hash ===" >&2

      if git rev-list --quiet -n1 "$hash" >/dev/null 2>&1; then
        info "Patch already applied, skipping"
      elif { echo "$patch" | git am --ignore-date; }; then
        info "Applied patch successfully"
      else
        git am --show-current-patch
        git am --abort || true
        info "Apply patch failed, rebasing"
        sync_force "$LOCAL"
      fi
      patch=
    else
      patch="$patch$line
"
    fi
  done
}

sync_force "$LOCAL"

start_pull &
echo $! >> "$lock_file"

start_push &
echo $! >> "$lock_file"

if test ! "$no_autosync"; then
  autosync &
  echo $! >> "$lock_file"
fi

wait
