#!/bin/sh
set -e

# shellcheck source=common.sh
. "$(dirname "$(realpath "$0")")/common.sh"

while test "$1"; do
  case "$1" in
    -f|--force) force=1;shift;;
    -*) die "$1 is not an option";;
    *) arg="${1:-.}";shift;;
  esac
done

arg="${arg:-.}"
if test -f "$arg"; then
  LOCAL="$(cd "$(dirname "$arg")";pwd)"
  LOCAL_FILE="$LOCAL/$(basename "$arg")";
else
  LOCAL="$(cd "$arg";pwd)";
  LOCAL_FILE="$LOCAL";
fi
setrepo "$LOCAL"

if test -n "$force"; then
  sync_force "$LOCAL_FILE"
else
  sync_patch "$LOCAL_FILE" || info "Nothing to sync"
fi
