#!/bin/sh
set -e

# shellcheck source=common.sh
. "$(dirname "$(realpath "$0")")/common.sh"

setrepo .
git log --graph --color --date=relative --pretty=format:'%C(auto)%h %Cblue<%an>%Creset edited %ad' "$@"
