#!/bin/sh
set -e

# shellcheck source=common.sh
. "$(dirname "$(realpath "$0")")/common.sh"

while test "$1"; do
  case "$1" in
    -q|--quiet) quiet=1;shift;;
    -*) die "$1 is not an option";;
    *) LOCAL="$1";shift;;
  esac
done

path="$(pairon_path "${LOCAL:-.}")"
test "$quiet" || echo "$path"
