#!/bin/sh
set -e

USAGE='Usage: pairon-sync [OPTIONS..] [LOCAL]

Get local repo up to date with remote.

LOCAL - Local repo path (default: .)

Options:
    --help, -h          Show this message
    --force, -f         Force a full sync
'

# shellcheck source=lib/common.sh
. "$(dirname "$(realpath "$0")")/../lib/common.sh"

while test "$1"; do
  arg="$1";shift
  case "$arg" in
    --help|-h) usage;;
    --force|-f) force=1;;
    -*) usage "'$arg' is not an option";;
    *)
      test "$LOCAL" || { LOCAL="$arg";continue; }
      usage "'$arg' is not an option";;
  esac
done

LOCAL="${LOCAL:-.}"

if test -f "$LOCAL"; then
  LOCAL_PATH="$(cd "$(dirname "$LOCAL")";pwd)"
  LOCAL_FILE="$LOCAL_PATH/$(basename "$LOCAL")";
else
  LOCAL_PATH="$(cd "$LOCAL";pwd)";
  LOCAL_FILE="$LOCAL_PATH";
fi

setrepo "$LOCAL_PATH"

if test "$force"; then
  sync_force "$LOCAL_FILE"
else
  sync_patch "$LOCAL_FILE" || info "Nothing to sync"
fi
