#!/bin/sh
set -e

# shellcheck source=lib/common.sh
. "$(dirname "$(realpath "$0")")/../lib/common.sh"

COMMANDS="$(find "$LIBEXEC_DIR" -type f -name 'pairon-*' | sed 's/.*pairon-//' | sort | uniq)"

USAGE='Usage: pairon COMMAND [OPTIONS..]

Options:
    --help, -h    Show this message

    Every other option is passed to the specific command.

Commands:
'"$(echo "$COMMANDS" | sed 's/^/    /')"

while [ "$1" ]; do
  arg="$1";shift
  case "$arg" in
    --help|-h) usage;;
    *)
      test "$CMD" || { CMD="$arg"; }
      break
  esac
done

test "$CMD" || usage "No command given"

if echo "$COMMANDS" | grep -Eq "^$CMD$"; then
  exec "$LIBEXEC_DIR/pairon-$CMD" "$@"
else
  usage "'$CMD' is not a command"
fi
