#!/bin/sh
set -e

USAGE='Usage: pairon-log [OPTIONS..]

Show change history.

Options:
    --help, -h    Show this message
'

# shellcheck source=lib/common.sh
. "$(dirname "$(realpath "$0")")/../lib/common.sh"

arg="$1"
case "$arg" in
  --help|-h) usage;;
esac

setrepo .
git log --graph --color --date=relative --pretty=format:'%C(auto)%h %Cblue<%an>%Creset edited %ad' "$@"
