#!/bin/sh
set -e

USAGE='Usage: pairon-remote [OPTIONS..]

Print remote URLs.

Options:
    --help, -h    Show this message
'

# shellcheck source=lib/common.sh
. "$(dirname "$(realpath "$0")")/../lib/common.sh"

while test "$1"; do
  arg="$1";shift
  case "$arg" in
    --help|-h) usage;;
    *) usage "'$arg' is not an option";;
  esac
done

setrepo .
git remote -v | awk '{ gsub(/\/\.pairon$/, "", $2); print $2, $3 }'
