#!/bin/sh
set -e

USAGE='Usage: pairon-git [GIT_OPTIONS..]

Use git commands on the .pairon bare repo.

All arguments are passed to `git`.
'

# shellcheck source=lib/common.sh
. "$(dirname "$(realpath "$0")")/../lib/common.sh"

setrepo .
git "$@"
