#!/bin/sh
set -e

USAGE='Usage: pairon-init [IGNORE..]

Make a new pairon repo in current directory.

IGNORE     List of files to add to .pairon/ignore file

Options:
    --help, -h        Show this message
    --no-commit, -n   Don'"'"'t commit files in directory
'

# shellcheck source=lib/common.sh
. "$(dirname "$(realpath "$0")")/../lib/common.sh"

while test "$1"; do
  arg="$1";shift
  case "$arg" in
    --help|-h) usage;;
    --no-commit|-n) no_commit=1;;
    -*) usage "'$arg' is not an option";;
    *)
      test "$LOCAL" || { LOCAL="$arg";continue; }
      usage "'$arg' is not an option";;
  esac
done

mkrepo() {
  (cd "$1" || exit 1
    export GIT_WORK_TREE="$PWD"
    export GIT_DIR="$GIT_WORK_TREE/.pairon"
    git init --share=group --template="$TEMPLATE_DIR"
    initrepo "$PWD"
    if test ! "$no_commit"; then
      git add .
      git commit --allow-empty -m "pairon auto inito" || true
    fi
  )
}

echo "$LOCAL" | grep -q : && remote_mode=1

if test "$remote_mode"; then
  dest="$(mktemp -d "${TMPDIR:-/tmp}"/pairon.XXXXXXXX)"
  mkrepo "$dest"
  scp -r "$dest" "$LOCAL"
  rm -rf "$dest"
else
  {
    pairon_path "$LOCAL" >/dev/null 2>&1 && stop "This is already a pairon repo"
  } || true
  mkdir -p "$LOCAL"
  mkrepo "$LOCAL"
fi
