#!/bin/sh
set -e

USAGE='Usage: pairon-connect REMOTE [LOCAL] [OPTIONS..]

Porcelain for cloning/setting remote of a repo/directory and starting
`parion-listen`.

REMOTE    An URL to the pairon repo to clone (e.g. user@host:path)
LOCAL     Local path to clone repo to

Options:
    --help, -h    Show this message
'

# shellcheck source=lib/common.sh
. "$(dirname "$(realpath "$0")")/../lib/common.sh"

connect() {
  setrepo "$1"
  git remote add origin "$2/.pairon" 2>/dev/null \
    || git remote set-url origin "$2/.pairon" 2>/dev/null
  git push -u origin master >/dev/null 2>&1
}

while test "$1"; do
  arg="$1";shift
  case "$arg" in
    --help|-h) die;;
    -*) usage "'$arg' is not an option";;
    *)
      test "$REMOTE" || { REMOTE="$arg";continue; }
      test "$LOCAL" || { LOCAL="$arg";continue; }
      usage "'$arg' is not an option";;
  esac
done

LOCAL="${LOCAL:-.}"

if test -n "$REMOTE"; then
  REMOTE_FILE="${REMOTE#*:}"
  echo "$REMOTE" | grep -q : && ssh_mode="ssh ${REMOTE%%:*} -- "

  $ssh_mode test -d "$REMOTE_FILE" || remote_empty=1
  test -d "$LOCAL" && test -n "$(find "$LOCAL"/* -maxdepth 0 2>/dev/null)" || local_empty=1

  if test -n "$local_empty" && test -n "$remote_empty"; then
    pairon init "$REMOTE"
    pairon clone "$REMOTE" "$LOCAL"
  elif test -z "$local_empty" && test -n "$remote_empty"; then
    pairon init --no-commit "$REMOTE"
    pairon path >/dev/null || pairon init "$LOCAL"
    connect "$LOCAL" "$REMOTE"
  elif test -n "$local_empty" && test -z "$remote_empty"; then
    pairon clone "$REMOTE" "$LOCAL"
  elif test -z "$local_empty" && test -z "$remote_empty"; then
    if pairon path >/dev/null; then
      die "This directory is already connected.

  Remove '$(pairon path)/.pairon' to connect to a different remote."
    fi
    dest="$(mktemp -d "${TMPDIR:-/tmp}"/pairon.XXXXXXXX)"
    pairon clone "$REMOTE" "$dest"
    mv "$dest/.pairon" "$LOCAL/"
    rm -rf "$dest"
  fi
fi

pairon listen "$LOCAL"
