#!/bin/sh
set -e

USAGE='Usage: pairon-ignore [FILES..]

Add files to pairons ignore list and print list.

FILES     List of files to add to .pairon/ignore file

Options:
    --help, -h    Show this message
'

# shellcheck source=lib/common.sh
. "$(dirname "$(realpath "$0")")/../lib/common.sh"

setrepo .

files=""

while [ "$1" ]; do
  arg="$1";shift
  case "$arg" in
    --help|-h) usage;;
    -*) usage "'$arg' is not an option";;
    *)
      files="$files\n$(realpath --relative-to="$GIT_WORK_TREE" "$arg")"
      ;;
  esac
done

ignore_file="$GIT_WORK_TREE/$(git config core.excludesFile)"
touch "$ignore_file"

echo "$files" | while read -r file; do
  if [ "$file" ] && ! grep -q "^$file$" "$ignore_file"; then
    echo "$file" >> "$ignore_file"
  fi
done

# Remove files from the index if they are ignored
( cd "$GIT_WORK_TREE"
  remove="$(git ls-files -i -c --exclude-from "$ignore_file")"
  if [ "$remove" ]; then
      echo "$remove" | xargs -L1 git rm --cached
  fi
)

echo >&2 "Ignoring:"
cat "$ignore_file"
