#!/bin/sh
set -e

export TZ=UTC
unset XDG_CONFIG_HOME
unset HOME
export GIT_CONFIG_NOSYSTEM=1

while read OLDSHA NEWSHA REF; do
  for SHA in `git rev-list --reverse $OLDSHA..$NEWSHA`; do
    git format-patch --stdout -p $SHA^..$SHA;echo ___END_OF_MESSAGE___
  done >> produce
done

cd ..
GIT_DIR=.pairon git reset --hard
